CREATE TABLE IF NOT EXISTS `satanbarbara`.`bands` (
    `id` INT(11) NOT NULL AUTO_INCREMENT, 
    `created` TIMESTAMP NOT NULL DEFAULT 0,
    `name` VARCHAR(255) NOT NULL, 
    `genre` INT(11) NOT NULL, 
	`members` VARCHAR(255) NOT NULL,
    `last_login` TIMESTAMP NOT NULL DEFAULT 0,
    `last_active` TIMESTAMP NOT NULL DEFAULT 0,
    `last_activated` TIMESTAMP NOT NULL DEFAULT 0,
    `last_modified` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP,
    `activated` BOOLEAN NOT NULL DEFAULT 0,
    `suspended` BOOLEAN NOT NULL DEFAULT 0,
    `banned` BOOLEAN NOT NULL DEFAULT 0,
    `deleted` BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`) 
) ENGINE=`InnoDB` DEFAULT CHARSET=`utf8` COLLATE=`utf8_unicode_ci` AUTO_INCREMENT=1;